apiVersion: v1
kind: Service
metadata:
  name: {{ include "grid-dynamics-website.fullname" . }}
spec:
  selector:
    app: {{ include "grid-dynamics-website.name" . }}
  ports:
    - port: 80
      targetPort: 80
  type: {{ .Values.service.type }}

