apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: test-grid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
  template:
    metadata:
      labels:
        app: testgrid
    spec:
      containers:
      - name: testgrid
        image: shashankssriva/mymusicstats-arm64:1.0.2
        ports:
        - containerPort: 80
