apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # Must match the label in the deployment
  ports:
    - protocol: TCP
      port: 80       # Port exposed by the service
      targetPort: 80  # Port in the container
  type: ClusterIP  # You can change it to LoadBalancer or NodePort if needed
